var title = document.getElementById('title');
var lists = document.getElementById('list');
var listArray = [
    'Variables',
    'Functions',
    'Loops',
    'Conditional Statements',
    'Conditional Operators'
];

title.innerHTML = 'Title generated by javascript';

for (var i = 0; listArray.length > i; i++){
    var list = document.createElement('li');
    list.innerHTML = listArray[i];

    lists.appendChild(list);
}
